### ISSUE TITLE
希望能支持注入自定义expire方法

### ISSUE THREAD

**Issue by zdpdpdp** [pippishrimp/guava_cache#1]
缓存获取成功后，希望能调用注入的的expire() bool 方法， 返回true 以后再调用loader

**Comment by weletry** [comment]
你的目的是想查看key是否过期，再决定是否load吗？

**Comment by zdpdpdp** [comment]
> 你的目的是想查看key是否过期，再决定是否load吗？

是的，或者说我想要用自己的逻辑来决定是否过期
